server:
  port: 9090
  servlet:
    context-path: /api

#mybatis配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.smart.star.entity
  configuration:
    map-underscore-to-camel-case: true


#spring相关
spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 2MB
      max-request-size: 10MB

  main:
    lazy-initialization: true
  #druid连接池
  datasource:
    username: admin
    password: EkUWKYcoACOC0G8JYSGCfoQYQPW4cBqNDwmENGzR7t6wj6j0JyUTArrltsCstcSNhf7Mo/dnPWHUmA52IqITEg==
    publicKey: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBALhl0OKbP5NbluqVPCgC9rZjdh+CQk8C/u7N9XE2aa/RGymJsJHK0+FOTi8wYGcoXuG5hul6E3iwNFmdv0o+CAUCAwEAAQ==
    connection-properties: config.decrpt=true;config.decrypt.key=${spring.datasource.druid.publicKey}
    url: jdbc:mysql://47.98.144.194:3306/mall?useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      #2.连接池配置
      #初始化连接池的连接数量 大小，最小，最大
      initial-size: 5
      min-idle: 5
      max-active: 20
      #配置获取连接等待超时的时间
      max-wait: 60000
      #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 30000
      validation-query: SELECT 1 FROM DUAL


  security:
    loginType: JSON